### PR TITLE
Add update hostname method

### PR DESCRIPTION
**Pull request by goldbergjeffrey**
Added an update hostname method so that hostname can be changed on the fly in a qrsInteract instance.

### CODE REVIEW

**Comment by goldbergjeffrey** [comment]
@jparis FYI *down arrow*

**Review by jparis — APPROVED** [review]
Good.. the spacing is annoying though.

**Comment by jparis** [comment]
bootstrapped a change onto your PR @goldbergjeffrey. want to take a look?

**Comment by jparis** [comment]
Will publish a new version when this gets merged.

**Review by goldbergjeffrey — COMMENTED** [review]
so I see the change for url encoding, but what happens if the path being sent in is already url encoded?  If it is done twice is that a problem?  Is there a way to check for url encoding?

**Pull request merged**
